---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:

- name: amazonlinux
  driver:
    image: amazonlinux:latest
    intermediate_instructions:
      - RUN yum -y install upstart procps util-linux
    pid_one_command: /sbin/init
    
suites:
  - name: setup
    driver:
      chef_version: latest
    run_list:
    - recipe[dokken_test::setup]

  - name: blank
    driver:
      chef_version: latest
    run_list:
    - recipe[dokken_test::blank]
