---
driver:
  name: dokken
  chef_version: latest
  privileged: true
  volumes: [ '/var/lib/docker' ]
  
transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:

- name: amazonlinux
  driver:
    image: amazonlinux:latest
    intermediate_instructions:
      - RUN yum -y install upstart procps util-linux
    pid_one_command: /sbin/init
    
suites:
  - name: default
    driver:
      chef_version: latest
    run_list:
    - recipe[dokken_test::default]

  - name: hello
    driver:
      chef_version: latest
    run_list:
    - recipe[dokken_test::hello]

  - name: helloagain
    driver:
      chef_version: latest
    run_list:
    - recipe[dokken_test::helloagain]
    
